### ISSUE TITLE
DNS packets not being received by client

### ISSUE THREAD

**Issue by taylorj91** [LipiLee/ToyShark#6]
Hello, I really appreciate the effort you put forth to maintain this wonderful project.
I've been playing with it and trying to test it out with my own DNS server, and I've noticed the client doesn't seem to receive the DNS responses when DNS traffic goes through the vpn.

I'm very inexperienced, but would you mind providing any recommendations to solving this?
I'm currently just adding the following line to ToySharkVPNService.java line 380 in the method startVpnService( ):

 
> Builder builder = new Builder()
> 				.addAddress("10.120.0.1", 32)
> 				.addRoute("0.0.0.0", 0)
> 				.addDnsServer("8.8.8.8") // added this line
> 				.setSession("ToyShark");

Have you successfully been able to allow DNS traffic through the VPN and still forward packets to and from the client?

**Comment by taylorj91** [comment]
@LipiLee any suggestions on this?

**Comment by LipiLee** [comment]
@taylorj91  Thanks for your report and sorry that response is so late because of Chuseok(Korean Thanksgiving) and debugging it. UDP packets has been dropped in kernel's network stack due to the invalid checksum in its IP header. I have already fixed this issue. So you can check it after pull.

**Comment by taylorj91** [comment]
Thank you so much for this fix! Works great now!
